### ISSUE TITLE
More than one locale?

### ISSUE THREAD

**Issue by Arbars** [eighttails/PC6001VX#10]
Hi!
First of all, thank you for your work!
 I'm making russian localization for this emulator, and, when I'm trying to test it, locale stay the same.
 After research I found the point of plugging  the locale files:
 ```

 	if(locale.language() != QLocale::Japanese){
		qDebug() << "LANG = " << locale;
		if (myappTranslator.load(":/translation/PC6001VX_en")) {
			app.installTranslator(&myappTranslator);
		}
```
It is possible to change it for more than one locale support?

**Comment by eighttails** [comment]
Thanks for translation.
I changed loading order of language file.
https://github.com/eighttails/PC6001VX/commit/765567df0eae89316706ade32ab36e30e30aea80

1. If system language is Japanese load no translation. (display hardcoded japanese)
2. System language if translation found.
3. Display English.(fallback)
