### ISSUE TITLE
Android 13.0 Pixel 4a でタッチ位置検出が意図通りになっていない?

### ISSUE THREAD

**Issue by tsutsui** [eighttails/PC6001VX#14]
PC6001VX 4.2.4 において Android 13.0 Pixel 4a でタッチ位置の検出が意図どおりになっていないように見えます。

詳細は添付動画を見ていただくとして、以下が意図通りでないように見えます。

* 画面の上端の数ドットの範囲はタッチしても反応しない?  （00:04〜00:05; 厳密なタッチ範囲を確認できていませんが）
* 仮想キーボードを消去しても画面の再描画がされない  （00:10〜00:11）
* 画面回転後の横画面でのタッチ位置の反応範囲が画面サイズと一致しない、
かつ、タッチ位置とメニュー表示位置がずれる （00:22〜00:30）
* 仮想キーボードを再表示したときの縦位置が下にズレている、かつ、タッチ範囲がおかしい? （00:32〜00:38）

https://github.com/eighttails/PC6001VX/assets/3054480/ce7732a5-1ca0-4864-9f14-4278d217665f

なお、仮想キーボード消去後の横画面でのタッチ範囲のズレについては 4.2.3でも同様だったと思います。

**Comment by eighttails** [comment]
58f4cd6dd733b0222f377e96ea59725e9c926794
9d0465033b8828caba01c21b6cf3fd34c6ba5c77
で修正しました。
リリースはしばらくお待ちください。
