### ISSUE TITLE
PC6001VX 4.2.5 does not run for 14-arm

### ISSUE THREAD

**Issue by chenrui333** [eighttails/PC6001VX#15]
👋 happy new year, I have just ran into another issue of launching PC6001VX 4.2.5 on a 14-arm machine (while it does work for 13-arm machine)

```
$ lldb /opt/homebrew/Cellar/pc6001vx/4.2.5/bin/PC6001VX
(lldb) target create "/opt/homebrew/Cellar/pc6001vx/4.2.5/bin/PC6001VX"
error: '/opt/homebrew/Cellar/pc6001vx/4.2.5/bin/PC6001VX' doesn't contain any 'host' platform architectures: arm64, armv7, armv7f, armv7k, armv7s, armv7m, armv7em, armv6m, armv6, armv5, armv4, arm, thumbv7, thumbv7k, thumbv7s, thumbv7f, thumbv7m, thumbv7em, thumbv6m, thumbv6, thumbv5, thumbv4t, thumb, x86_64, x86_64, arm64, arm64e, arm64, arm64e
```

this is the working snapshot for 13-arm

![image](https://github.com/eighttails/PC6001VX/assets/1580956/da0948fe-aa55-4d03-98c8-f082f761db4d)

Let me know if you need more info. Thanks!

**Comment by eighttails** [comment]
I can't resolve Mac binary issue because I don't have Mac and I am not involved in homebrew development.
Please post issue to homebrew repo.
