### ISSUE TITLE
`4.2.5` doesn't quit gracefully with SIGTERM or SIGHUP

### ISSUE THREAD

**Issue by bevanjkay** [eighttails/PC6001VX#16]
At `homebrew-core` we are seeing a recurring test issue with `PC6001VX` where we cannot run the application twice in a row, if it is quit using "SIGTERM", or similar `kill` commands.

I can replicate this by running the built binary on my machine, forcefully quitting it (without responding to the config prompts that show on first start), and then trying to run the binary again (it will crash immediately). If I restart my machine and try again the binary then functions.

Here is a link to our current `test` for reference: https://github.com/Homebrew/homebrew-core/blob/900d197baaaf7ea18a89ba06a76c0ed5f9144e97/Formula/p/pc6001vx.rb#L38-L52

It may be that QT is not setup to gracefully handle unix's SIGTERM or SIGHUP commands.
https://doc.qt.io/qt-6/unix-signals.html

**Comment by eighttails** [comment]
I can't reproduce on Mac because I don't have Mac.
However I confirmed the issue on Linux and fixed.
See if HEAD version works.
93f2a366d1944237d4712a6de4290ac1bda15771

**Comment by bevanjkay** [comment]
It is close!
If the window "ROM files not found" is showing when the signal is sent, it only closes that window, then a second is spawned "Do you want to use the built-in compatible ROM?"

I can send SIGTERM again and it will then close, which works for now, but it should probably stop the whole instance on SIGTERM.

**Comment by eighttails** [comment]
I tried to reproduce on Linux but it quits on first signal and "Do you want to use the built-in compatible ROM?" dialog was not shown.
On Mac it seems  SIGTERM to QMassagebox is mapped to close or "No" button(?)
