### ISSUE TITLE
error ?SN Error in 40704 in game Vital Lamp with non built in pc-6001mk2/6601 bios

### ISSUE THREAD

**Issue by datadragon00** [eighttails/PC6001VX#5]
Version 3.3.1 windows 10. I receive an error ?SN Error in 40704 when trying to load and run game Vital Lamp (5, page 2) and get errors with other games also when using real bios for 6001mk2 or 6601 instead of built in compatible rom. I first ran the game with no problem using the built in bios set to 6601 as the model and the game worked. I then tried to unselect use the built in compatible rom and selected 6001mkII as the model. I have the bios roms in the rom directory, set the subdirectory for rom and set the rom to BASICROM.62 in that directory. It boots ok to say pc-6001 mk2 basic, I can select the 5 n60m basic and then page 2. Added the vital lamp tape in right click menu, cload worked but next when I typed run I get a ?SN Error in 40704. So not sure what is wrong as that did not happen with built in bios. Same error occurs if I try 6601 bios not built in and selecting BASICROM.66 from the rom directory and PC-6601 as the model with built in rom unselected, but works if I use built in rom. I then tried several bios rom sets also including this set as an example that works fine in another emulator so I dont think it is the bios unless it needs a different name. https://mega.nz/#!yugQDCqY!KZSDhtveWfBtMtP8Qx8s-GudQO7hdkIxOciNmjjuX7c

The free game appears to be in this collection https://archive.org/details/Neo_Kobe_NEC_PC-6001_2016-02-25  Twinkle stars (5,2) also had a similar problem as another example giving a ?SN Error in 36352 on the run command using the non built in bios.

**Comment by eighttails** [comment]
This is known issue of upstream PC6001V and I'm not able to fix it.
A workaround exists. Menu -> Settings -> Boost up.
Boost up makes tape loading faster and stable when tape is read via bios routine.
(If the program uses its own loading routine, it's a different story.)
